### ISSUE TITLE
where is ./util/orca

### ISSUE THREAD

**Issue by yangzhao1230** [cvignac/DiGress#10]
hi,

you mentioned "Navigate to the ./util/orca directory and compile orca.cpp: g++ -O2 -std=c++11 -o orca orca.cpp", but i did't find ./util/orca.

thanks a lot

**Comment by zyxNova** [comment]
I found the same problem and fixed it:
Navigate to the `./src/analysis/orca` directory and compile orca.cpp: `g++ -O2 -std=c++11 -o orca orca.cpp`
Hope it helps you too.

**Comment by yangzhao1230** [comment]
@zyxNova I appreciate your help so much!

**Comment by cvignac** [comment]
Thanks @zyxNova for answering, I had forgotten to change the instructions after the code refactor. I will update the README!
