### ISSUE TITLE
A Little Question about you paper

### ISSUE THREAD

**Issue by LeavesLi1015** [cvignac/DiGress#11]
Hello, I'm reading about your paper and I really love your work! But I still have a little question about the quation(1) in your paper. Is there any detailed proof of it? Thank you very much!
<img width="679" alt="image" src="https://user-images.githubusercontent.com/76167689/221857942-5946f052-176e-43a5-b476-a2713c8bba44.png">

**Comment by cvignac** [comment]
Hi @LeavesLi1015, I added the proof in the latest version of the paper on Openreview, so that people don't have to figure it out by themselves: **https://openreview.net/pdf?id=UaAD-Nu86WX**
it's in Appendix D, page 17.
Best,
Clement

**Comment by LeavesLi1015** [comment]
Thank you very much! It helps me a lot!
