### ISSUE TITLE
Question about FiLM layer

### ISSUE THREAD

**Issue by LeavesLi1015** [cvignac/DiGress#16]
As it's mentioned in the 3.2 DENOISING NETWORK PARAMETRIZATION and Appendix B, a FiLM layer is used to incorporate edge feature and global feature. Why do you use FiLM layer and What other layer did you try for incorporation?

**Comment by cvignac** [comment]
Hello,
FiLM layers are a general way to aggregate information coming from different sources, and it has been used successfully in many settings. We didn't try anything else. There are so many ways to create architecture that manipulate both node level, edge level and graph level information that we had to make choices without trying different options.

Clement
