### ISSUE TITLE
Question in “python3 guidance/train_qm9_regressor.py +experiment=regressor_model.yaml”

### ISSUE THREAD

**Issue by flick-ai** [cvignac/DiGress#17]
We try to run the code as command in title, but we find that target is [] in qm9_regressor_discrete.py, line 170. Can you provide any suggestions ？ Thanks.

**Comment by rohanasthana** [comment]
Hi,
I am also having this issue. I tried deleting the dataset and checking all the 'guidance_target' values in regressor_model.yaml . Can you please help me out with this?

**Comment by cvignac** [comment]
Hello, I have pushed a fix in qm9_dataset.py. Can you try and tell me if it works? You shouldn't have to delete the dataset again.
Clement
