### ISSUE TITLE
error occur when "Navigate to the ./src/analysis/orca directory and compile orca.cpp: `g++ -O2 -std=c++11 -o orca orca.cpp"`

### ISSUE THREAD

**Issue by Lyris01** [cvignac/DiGress#18]
orca.cpp: In function ‘int writeResults(int, const char*)’:
orca.cpp:1341:13: warning: control reaches end of non-void function [-Wreturn-type]
 1341 |     fstream fout;
      |             ^~~~
orca.cpp: In function ‘int writeEdgeResults(int, const char*)’:
orca.cpp:1374:13: warning: control reaches end of non-void function [-Wreturn-type]
 1374 |     fstream fout;
      |             ^~~~

**Comment by anar-rzayev** [comment]
As far as I know, the warnings are related to control flow and indicate that the compiler is not able to determine whether the function will return a value. The warning message "control reaches the end of non-void function" means that there is a path in the function where the execution may reach the end of the function without returning a value. This can happen if a conditional statement or loop does not cover all possible cases, or if there is an early exit statement (such as a return statement) that bypasses the return statement at the end of the function.
To fix the warning, maybe you can add a return statement at the end of the function, or you can add a default return statement before the end of the function that returns a default value in case none of the other return statements are executed. Can you maybe share the orca.cpp, is it exactly same as the original repo file?
