### ISSUE TITLE
TypeError: EMA.on_save_checkpoint: return type `<class 'dict'>` is not a `<class 'NoneType'>`

### ISSUE THREAD

**Issue by Layne-Huang** [cvignac/DiGress#2]
Hi,

I met the error when I ran the main.py which imports the utils.py file: TypeError: EMA.on_save_checkpoint: return type `<class 'dict'>` is not a `<class 'NoneType'>`.
![image](https://user-images.githubusercontent.com/34830172/211262455-c1579bd0-e8c6-4e00-8e06-7a0c35696248.png)

Could you pls help me solve this issue?

Thank you very much.

**Comment by cvignac** [comment]
Hello Layne-Huang, I cannot reproduce this error. Could you tell me the version of pytorch_lightning that you use (using `pip list`) and upgrade to `1.7.2` if you have another version?

**Comment by Layne-Huang** [comment]
Thank you for your reply.

The pytorch_lighting that I use is 1.8.6.

Should I downgrade to 1.7.2?
