### ISSUE TITLE
Implementation of FiLM y to E?

### ISSUE THREAD

**Issue by najwalb** [cvignac/DiGress#25]
There is a comment on this [line](https://github.com/cvignac/DiGress/blob/2573f9c5854841d05468d245fb835dab537ccba0/src/models/transformer_model.py#L116) pointing out that you're using dx instead of de when computing FiLM from y to E. Shouldn't it be de actually?

**Comment by cvignac** [comment]
This layer is used after flattening the heads, which explains why it's d_x and not d_e

**Comment by najwalb** [comment]
noted thanks.
