### ISSUE TITLE
what is compute_extra_data?

### ISSUE THREAD

**Issue by lihuiliullh** [cvignac/DiGress#26]
May I know what the purpose of function "compute_extra_data"?
I could not find it in the paper. 

![image](https://user-images.githubusercontent.com/53407011/229225758-1d2ca249-4100-46f2-a4e4-f47bcba49629.png)

**Comment by najwalb** [comment]
It's section 4.2 and appendix B1. Extra features is extra graph features (spectral features, cycle counts, etc). Domain features adds domain specific graph features, like properties of molecules (valency etc).
