### ISSUE TITLE
problem in multi-GPU setting

### ISSUE THREAD

**Issue by zzzzihyun** [cvignac/DiGress#29]
Thanks for sharing your great work!

I have a problem. I want to run experiments using the guacamol dataset, but it's not possible to train on a single GPU(3090).
Do you have a multi-GPU version of the code available, even if it's not well-organized?
I would appreciate it if you could provide some guidance or resources on how to set up multi-GPU training in PyTorch.

Thank you:)

**Comment by cvignac** [comment]
Hello, you can look at the code of MiDi (https://github.com/cvignac/midi) where we added multi-gpu support. One of the things that you need to change is the logging, because if you don't, each gpu will log the metrics and it will be a mess.
