### ISSUE TITLE
How to run the code in multi-gpu mode

### ISSUE THREAD

**Issue by Layne-Huang** [cvignac/DiGress#3]
Dear authors,

I am sorry to bother you. I ran the code by ddp, however, it threw out errors like this "RuntimeError: The size of tensor a (128) must match the size of tensor b (0) at non-singleton dimension 1". I also noticed that you said that this branch is not implemented for multi-gpu.  Could you please tell me which part should be modified to adapt it for ddp mode?

Best regards,
Lei

**Comment by Layne-Huang** [comment]
I have solved this issue by changing the y_dim from 0 to 1.

**Comment by cvignac** [comment]
Perfect, does everything work now?

If you encounter problems with the metrics because every process is logging to wandb, you can add

if self.local_rank == 0:
    utils.setup_wandb(self.cfg)
and then

if wandb.run:
    wandb.log(…)

Clément

**Comment by Layne-Huang** [comment]
Yes, but it always threw out "AttributeError: _old_init" although I have used setup function rather than prepare_data function which is not suitable for DDP mode. 

Besides, I am wondering why you set the second dimension of y as 0 rather than 1. Could you please give me some insights?

**Comment by cvignac** [comment]
We let the option to have some graph-level prediction but did not use it in the end. That's why we ended up with a layer of size 0.
For the _old_init, check if you can upgrade to lightning==1.7.2. The issue has been solved, as far as I know.

Clément

**Comment by koalaaaaaaaaa** [comment]
> I have solved this issue by changing the y_dim from 0 to 1.

@Layne-Huang Thanks for your solution! But due to my little knowledge in this area, I'm confused about what do you mean `y_dim`, and how to change it from 0 to 1?
Thank you again for your kindest reply!

**Comment by clclclaiggg** [comment]
> 



> > I have solved this issue by changing the y_dim from 0 to 1.
> 
> @Layne-Huang Thanks for your solution! But due to my little knowledge in this area, I'm confused about what do you mean `y_dim`, and how to change it from 0 to 1? Thank you again for your kindest reply!

Have you solved the problem？
