### ISSUE TITLE
For the given value on nodes and edges

### ISSUE THREAD

**Issue by DDigimon** [cvignac/DiGress#34]
Hi, I have read your code and tried to use your model on our own dataset. I noticed that you defined some values on nodes and edges. For example,

`            self.n_nodes = torch.tensor([0, 2.2930e-05, 3.8217e-05, 6.8791e-05, 2.3695e-04, 9.7072e-04,
                                         0.0046472, 0.023985, 0.13666, 0.83337])
            self.node_types = torch.tensor([0.7230, 0.1151, 0.1593, 0.0026])
            self.edge_types = torch.tensor([0.7261, 0.2384, 0.0274, 0.0081, 0.0])`

in the qm9_dataset, QM9infos. I'm wondering how to get these values if I want to apply DiGress to my own dataset. And is there any code to generate these values? 
Thanks a lot!

**Comment by cvignac** [comment]
Hello,
these are the distributions of number of nodes, node types and edge types. You can use the functions node_counts, node_types, edge_types of the class AbstractDataModule for the automatic computation of these distributions. You can check spectre_dataset.py for example.

**Comment by DDigimon** [comment]
Thanks! I'll try to get my own distribution through this function!
