### ISSUE TITLE
Use of self.T when computing the L_t terms in the loss

### ISSUE THREAD

**Issue by najwalb** [cvignac/DiGress#35]
I am talking about [this](https://github.com/cvignac/DiGress/blob/2573f9c5854841d05468d245fb835dab537ccba0/src/diffusion_model_discrete.py#L352) line. I noticed Appendix E.2 of [(Kingma, 2021)](https://arxiv.org/pdf/2107.00630.pdf) mentions a multiplication by T/2 as an unbiased estimator of the sum. [D3PM](https://github.com/google-research/google-research/blob/adb32014f9960739bd51ea8e9318a5db1a30a99d/d3pm/text/diffusion.py#L2668) computes the sum explicitly (if I understood their code correctly). 

Is your multiplication by T also a form of unbiased estimator? Can you point me to any literature to understand how to derive this estimator?

**Comment by cvignac** [comment]
The T/2 in the Kingma paper comes from the Gaussian distribution, whereas here we have KL between discrete distributions. You can check the Austin paper for the computation, for example

**Comment by najwalb** [comment]
I think the 1/2 comes from the Gaussian distribution, T is used to replace the sum. From Kingma's appendix:

"To avoid having to compute all T terms when calculating the diffusion loss, we construct an unbiased estimator of LT (x) [...] This trivially yields an unbiased Monte Carlo estimator, by drawing random samples i ⇠ U{1,T}"

Afaik Austin does not use this estimator, they simply compute the sum for all the t terms (as mentioned [here](https://github.com/google-research/google-research/blob/adb32014f9960739bd51ea8e9318a5db1a30a99d/d3pm/text/diffusion.py#L2684)).  

I wanted to check that my understanding of the use of T is correct. What do you think?

**Comment by cvignac** [comment]
For the Kingma paper, that’s my understanding as well. However, in all cases it is only an estimator that is computed — the true likelihood is an expectation over the data distribution, while all we can compute is an estimator based on test samples.

**Comment by najwalb** [comment]
Sounds good, thanks for confirming!
