### ISSUE TITLE
KNodeCycles.k6_cycle correctness

### ISSUE THREAD

**Issue by haoming-codes** [cvignac/DiGress#36]
Do you by any chance have a reference for the 6-cycle count formula in Appendix B2? I am having a hard time matching the formula (or the implementation in KNodeCycles.k6_cycle) to that of [Chang and Fu 2003](https://www.math.nycu.edu.tw/research/DOWNLOAD_FILES/hlfu/85.%20The%20number%20of%206-cycles%20in%20a%20graph.pdf). Thank you!

**Comment by cvignac** [comment]
I think that we took it from https://mathworld.wolfram.com/GraphCycle.html
