### ISSUE TITLE
Extending molecule with partial charges

### ISSUE THREAD

**Issue by najwalb** [cvignac/DiGress#42]
Hi,

Is there any reason you only handle O+, N+, S+ in [molecule_with_partial_charge](https://github.com/cvignac/DiGress/blob/68394c8480852ff39310ce5ec1d8195bfa80abdc/src/analysis/rdkit_functions.py#L155)? I am wondering if it's possible to apply the same logic to all atom types and positive and negative charges?

Best,

**Comment by cvignac** [comment]
Hello, 
we used this to match the validity definition of GDSS, but we did not really use the partial charges for the final results reported in the paper.  
If you want to properly implement charges, I recommend to look at the code of MiDi: https://github.com/cvignac/midi
Generating charges as well allows to improve validity a lot on the complex datasets.

**Comment by najwalb** [comment]
Great thanks!
