### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException

### ISSUE THREAD

**Issue by vincenttsai2015** [cvignac/DiGress#46]
As I was executing the command "python3 guidance/train_qm9_regressor.py +experiment=regressor_model.yaml", an error message "pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `ExponentialLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler." occurred.
![image](https://github.com/cvignac/DiGress/assets/13366052/2eb9febd-0b85-4199-b808-8a17a9e7ab2b)
I'm wondering if I installed the wrong version of Pytorch (2.0 with CUDA 11.8) and Pytorch-geometric. 
Is it possible to solve this by downgrading the version of Pytorch or some other module? Thanks.

[Update 1]
As I tried to train a regressor after installing the guidance version according to the instruction (with Pytorch 1.11+CUDA11.3) of readme, a runtime error occurred: RuntimeError: object has no attribute sparse_csc_tensor

<img width="896" alt="image" src="https://github.com/cvignac/DiGress/assets/13366052/db7b1bec-01ee-4bcd-b08c-c0b9be2964c6">

[Update 2]
With Pytorch 1.10+CUDA 11.1, another error occurred as I tried to train a regressor after installing the guidance version according to the instruction: AttributeError: module 'distutils' has no attribute 'version'
<img width="941" alt="image" src="https://github.com/cvignac/DiGress/assets/13366052/e8f677b7-7cee-4cc0-a0be-f8990e5504cc">
I found the common solution is downgrading the version of setuptools, but if I try to downgrade the version of setuptools to <=59.5.0, running the code "train_qm9_regressor.py" will lead to "Segmentation fault (core dumped)"......
Is there anything else I can try? Thanks.

**Comment by cvignac** [comment]
Hello, the code was developed with torch_geometric==1.7 and cuda=11.3. 

You can try to downgrade to these versions. Before doing that, check that the segmentation fault is not related to the same problem as https://github.com/cvignac/DiGress/issues/48.

**Comment by vincenttsai2015** [comment]
I have tried the latest version of Pytorch, Pytorch Geometric, and Pytorch lightning equipped with CUDA 11.8, and solved this error after considerable modifications. Thanks.
