### ISSUE TITLE
Segmentation fault in the code aligning molecules for visualization

### ISSUE THREAD

**Issue by najwalb** [cvignac/DiGress#48]
From what I understood, you use this [code](https://github.com/cvignac/DiGress/blob/a83aa28363aa51a8df4d3d1945e087943ebc8712/src/analysis/visualization.py#L97) (until line 111) to align the molecules you plot in a chain. For certain molecules, the alignment causes a segmentation fault. Here is a minimal example to reproduce:

- Install rdkit and imageio following your instructions: 
```
conda create -c conda-forge -n test-digress rdkit python=3.9
conda activate test-digress
conda install pip
pip install imageio==2.26.1
```
- Run this minimal script using the correct example to benchmark, or the seg_fault/error example to see the error. If you comment the alignment code, both examples run normally. Make sure the molecule alignment code is uncommented in both cases:

```
import rdkit
from rdkit import Chem
from rdkit.Chem import Draw, AllChem
from rdkit.Geometry import Point3D
import numpy as np

import os
import imageio

def mol_from_graphs(node_list, adjacency_matrix):
    """
    Convert graphs to rdkit molecules
    node_list: the nodes of a batch of nodes (bs x n)
    adjacency_matrix: the adjacency_matrix of the molecule (bs x n x n)
    """
    # dictionary to map integer value to the char of atom

    atom_decoder = ['C', 'N', 'O', 'F']
    atom_decoder = atom_decoder

    # create empty editable mol object
    mol = Chem.RWMol()

    # add atoms to mol and keep track of index
    node_to_idx = {}
    for i in range(len(node_list)):
        if node_list[i] == -1:
            continue
        a = Chem.Atom(atom_decoder[int(node_list[i])])
        molIdx = mol.AddAtom(a)
        node_to_idx[i] = molIdx

    for ix, row in enumerate(adjacency_matrix):
        for iy, bond in enumerate(row):
            # only traverse half the symmetric matrix
            if iy <= ix:
                continue
            if bond == 1:
                bond_type = Chem.rdchem.BondType.SINGLE
            elif bond == 2:
                bond_type = Chem.rdchem.BondType.DOUBLE
            elif bond == 3:
                bond_type = Chem.rdchem.BondType.TRIPLE
            elif bond == 4:
                bond_type = Chem.rdchem.BondType.AROMATIC
            else:
                continue
            mol.AddBond(node_to_idx[ix], node_to_idx[iy], bond_type)

    try:
        mol = mol.GetMol()
    except rdkit.Chem.KekulizeException:
        print("Can't kekulize molecule")
        mol = None
    return mol

def plot_chain_molecules(mols, name='mols'):
    '''
        mols: list of RDKit molecule objects.
    '''
    # # code to align all molecules
    final_molecule = mols[-1]
    AllChem.Compute2DCoords(final_molecule)
    coords = []
    for i, atom in enumerate(final_molecule.GetAtoms()):
        positions = final_molecule.GetConformer().GetAtomPosition(i)
        coords.append((positions.x, positions.y, positions.z))

    for i, mol in enumerate(mols):
        AllChem.Compute2DCoords(mol)
        conf = mol.GetConformer()
        for j, atom in enumerate(mol.GetAtoms()):
            x, y, z = coords[j]
            conf.SetAtomPosition(j, Point3D(x, y, z))

    # generate frames for gif 
    frame_paths = []
    for frame in range(len(mols)):
        # if frame==0: 
        print(f'\nframe {frame}\n')
        file_name = os.path.join(f'{name}_fram_{frame}.png')
        Draw.MolToFile(mols[frame], file_name, size=(300, 300), legend=f"Frame {frame}")
        frame_paths.append(file_name)

    # save gif
    imgs = [imageio.imread(fn) for fn in frame_paths]
    gif_path = os.path.join(f'{name}.gif')
    print(f'gif_path {gif_path}\n')
    imgs.extend([imgs[-1]] * 10)
    imageio.mimsave(gif_path, imgs, subrectangles=True, fps=5)

    # save chains as grid
    img = Draw.MolsToGridImage(mols, molsPerRow=10, subImgSize=(200, 200))
    path_img = os.path.join(f'{name}_grid_image.png')
    print(f'path_img {path_img}\n')
    img.save(path_img)

if __name__ == '__main__':
    node_l_ref = np.array([0., 2., 2., 0., 0., 0., 1., 0., 2.], dtype=np.float32)
    adj_m_ref = np.array([[0., 0., 0., 0., 1., 0., 1., 0., 2.],
                        [0., 0., 0., 0., 0., 0., 0., 1., 3.],
                        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0., 0., 0., 3., 0.],
                        [1., 0., 0., 0., 0., 0., 4., 0., 2.],
                        [0., 0., 0., 0., 0., 0., 1., 1., 0.],
                        [1., 0., 0., 0., 4., 1., 0., 0., 1.],
                        [0., 1., 0., 3., 0., 1., 0., 0., 0.],
                        [2., 3., 0., 0., 2., 0., 1., 0., 0.]], dtype=np.float32)
    mol_ref = mol_from_graphs(node_l_ref, adj_m_ref)
    
    node_l_error = np.array([0., 2., 0., 0., 1., 0., 0., 0., 1.], dtype=np.float32)
    adj_m_error = np.array([[0., 4., 4., 0., 0., 3., 0., 4., 4.],
                        [4., 0., 3., 4., 4., 4., 1., 2., 4.],
                        [4., 3., 0., 4., 4., 1., 4., 2., 4.],
                        [0., 4., 4., 0., 4., 4., 4., 3., 4.],
                        [0., 4., 4., 4., 0., 1., 4., 4., 0.],
                        [3., 4., 1., 4., 1., 0., 4., 4., 4.],
                        [0., 1., 4., 4., 4., 4., 0., 4., 4.],
                        [4., 2., 2., 3., 4., 4., 4., 0., 4.],
                        [4., 4., 4., 4., 0., 4., 4., 4., 0.]], dtype=np.float32)
    mol_error = mol_from_graphs(node_l_error, adj_m_error)
    
    node_l_correct = np.array([0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=np.float32)
    adj_m_correct = np.array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
                        [1., 0., 0., 0., 1., 1., 1., 1., 0.],
                        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
                        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
                        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
                        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
                        [0., 1., 1., 0., 0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=np.float32)
    mol_correct = mol_from_graphs(node_l_correct, adj_m_correct)

    plot_chain_molecules(mols=[mol_ref, mol_correct], name='correct_aligned')
    # plot_chain_molecules(mols=[mol_ref, mol_error], name='seg_fault_aligned')
```
Note that all molecules I am using here were generated using a partially trained digress model on qm9 with a marginal transition and **no extra features**. Because the code throws a segmentation fault in these cases, the whole script fails (usually at the testing phase).

So my questions are:
1- Is this alignment necessary at all? I tried plotting without alignment and the molecules look reasonable, but perhaps harder to compare.
2- Did you try other ways of aligning the molecules? Using Rdkit's [AlignMol](https://www.rdkit.org/docs/source/rdkit.Chem.rdMolAlign.html) for example.
3- Any tips on avoiding this segmentation error?

Thanks in advance!

**Comment by najwalb** [comment]
I just tried with imageio 2.19.3 (from may 30, 2022) and it didn't help. It is rdkit that should be downgraded actually. The oldest version you can get from pip is 2022.3.3, and the example I have above works with it. Might be good to mention this in the readme.

I also posted about this in the [rdkit channel](https://github.com/rdkit/rdkit/issues/6430) because I don't think a segmentation fault is the best way to find out a feature is not possible anymore x)

Regarding the consistency of chains, I can't really see that it's beneficial for the intermediate plots. Sometimes the intermediate plots look more sensible when they're not aligned. For example, below you can see the 'correct' molecule from the example I gave above with and without alignment:
- With alignment:
![correct_aligned_grid_image](https://github.com/cvignac/DiGress/assets/107994360/75fcf438-a007-465f-a695-3c4bc6d67249)
- Without alignment:
![correct_grid_image](https://github.com/cvignac/DiGress/assets/107994360/6c388767-25f9-4d3a-ba17-b973e2a38b72)

It would also make sense to not align the molecules as everything changes between intermediate steps (atoms and edges), so it does not mean much to pin the first atom in the intermediate molecules in the same location as the first atom in the last molecule (I am also thinking of permuation invariance here).

**Comment by najwalb** [comment]
@koalaaaaaaaaa the rdkit version that worked for me is "2022.09.1'". They normally fixed this issue in the latest version of rdkit, so you can also update it from the latest commit on master (didn't try it yet).

**Comment by vincenttsai2015** [comment]
![image](https://github.com/cvignac/DiGress/assets/13366052/2fa22581-745b-4bac-9037-51a1eee78b52)
After updating rdkit, I encounter the following error when executing "python3 main.py +experiment=test.yaml" for training unconditional DiGress model:
```
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdDepictor.Compute2DCoords(Mol)
did not match C++ signature:
    Compute2DCoords(RDKit::ROMol {lvalue} mol, bool canonOrient=True, bool clearConfs=True, boost::python::dict {lvalue} coordMap={}, unsigned int nFlipsPerSample=0, unsigned int nSample=0, int sampleSeed=0, bool permuteDeg4Nodes=False, double bondLength=-1.0, bool forceRDKit=False)
```
Is there another possible solution to address the segmentation fault issue? Thanks.

**Comment by NajwaLaabid** [comment]
It sounds like the latest update changed the input arguments to Compute2DCoords. I would look into the code of Compute2DCoords and change the function call accordingly. If this doesn't work, I think it's worth asking on the RDKit repo directly, they're usually responsive.

**Comment by FairyFali** [comment]
> It sounds like the latest update changed the input arguments to Compute2DCoords. I would look into the code of Compute2DCoords and change the function call accordingly. If this doesn't work, I think it's worth asking on the RDKit repo directly, they're usually responsive.

I got the same error. Looking forward to your check results.
