### ISSUE TITLE
Checkpoint for QM9

### ISSUE THREAD

**Issue by jzenn** [cvignac/DiGress#59]
Hi Clement,

I'd like to thank you for this nice implementation! Do you have any checkpoint for a model trained on QM9 available that I can generate samples from or do I need to train from scratch?
Thank you in advance.

**Comment by jzenn** [comment]
I trained the model on QM9 with the default configuration. If anyone is interested in a checkpoint, shoot me a message.

**Comment by tjb-tech** [comment]
> I trained the model on QM9 with the default configuration. If anyone is interested in a checkpoint, shoot me a message.

May I ask for a checkpoint? My email address is jiabintang77@gmail.com. Thank you very much!

**Comment by koalaaaaaaaaa** [comment]
> I trained the model on QM9 with the default configuration. If anyone is interested in a checkpoint, shoot me a message.

May I ask for a checkpoint? My email address is 1595022729@qq.com. Thank you very much!

**Comment by Ripper346** [comment]
> I trained the model on QM9 with the default configuration. If anyone is interested in a checkpoint, shoot me a message.

Hi, I am interested in the checkpoint. Could you send me it? Thank you. My email is d354467885@gmail.com

**Comment by kkm0476** [comment]
> I trained the model on QM9 with the default configuration. If anyone is interested in a checkpoint, shoot me a message.

Hello! May I ask for a checkpoint? My email address is kkm0476@kaist.ac.kr. Thank you very much!

**Comment by XikunHuang** [comment]
> I trained the model on QM9 with the default configuration. If anyone is interested in a checkpoint, shoot me a message.

May I ask for a checkpoint? My email address is [huangxk1010@gmail.com](mailto:huangxk1010@gmail.com). Thank you very much!

**Comment by JazZyzJ** [comment]
May I ask for a checkpoint? My email address is [chenzijie040528@gmail.com](mailto:chenzijie040528@gmail.com). Thank you very much!
