### ISSUE TITLE
Reproducing NLL on QM9

### ISSUE THREAD

**Issue by pgmikhael** [cvignac/DiGress#6]
Hi,

Great paper, and really appreciate how well-documented the code is! I'm trying to run the discrete model on QM9 (just ```python main.py```), but my validation NLL seems to get stuck around 68-69 during training, and my test NLL is similarly high. Is this something you observe? Is there a different config / parameter values I should run in order to obtain ~23? 

Thank you!

**Comment by cvignac** [comment]
Hello Peter, 
there was some bugs in the likelihood computation at the time of the submission, please refer to the latest version or Arxiv. 

We have a likelihood of 69.6 on QM9, so your results look correct.

Clément

**Comment by pgmikhael** [comment]
Ah I see, thank you!! 

Do you happen to know what the reconstruction accuracy is (perfectly recovering the graph structure)? No worries if not!

**Comment by cvignac** [comment]
I've not compute it, sorry. Could you tell me exactly how you define it? I've seen it used for normalizing flows, but never for diffusion models.

**Comment by pgmikhael** [comment]
In this case, since the objective is predicting the correct node and edge class for each molecule, I was considering to check how often all nodes and edges are correctly predicted, averaged across molecules rather than total number of nodes/edges (and for any time step).

**Comment by cvignac** [comment]
In would be easy to compute indeed, but I don’t have it, sorry.

Clément
