### ISSUE TITLE
Discrepancy for MOSES dataset evaluation protocol

### ISSUE THREAD

**Issue by qiyan98** [cvignac/DiGress#61]
Hi,

I notice the number of molecules to generate for evaluation on MOSES dataset is `25000`, as specified in the config file.
https://github.com/cvignac/DiGress/blob/150ca149394ddbb32e855f4092b8dc1acdfce8f7/configs/experiment/moses.yaml#L17

The number of molecues are also `25000` in your shared SMILES samples: https://github.com/cvignac/DiGress/blob/main/generated_samples/generated_smiles_moses.txt.

However, the original MOSES paper suggests using `30000` generated samples for evaluation.
Snapshot:
<img width="1057" alt="Screenshot 2023-08-05 at 6 30 51 PM" src="https://github.com/cvignac/DiGress/assets/32333051/63da082b-be23-4cf9-ad2d-c7f5f19f0d02">
Source: https://arxiv.org/pdf/1811.12823.pdf#page=3

I'm new to this dataset and feel confused about the discrepancy. Can you explain why we choose 25000 instead of 30000?

Thanks,
Qi

**Comment by cvignac** [comment]
If you check the code of MOSES, I think that internally it uses 20000 valid samples to compute metrics. Since we can get enough valid molecules by sampling 25k molecules, we did not sample more.

**Comment by qiyan98** [comment]
Got it. Thanks!
