### ISSUE TITLE
Reproducing DiGress results on the Community-20 dataset

### ISSUE THREAD

**Issue by GhaliaRehawi** [cvignac/DiGress#65]
I am trying to reproduce the results of Digress on the small community-20 dataset.
Unfortunately, I can't get the results that you have in the paper, could you provide the list of hyperparameters that were used, basically the ones in general_default.yaml and train_default.yaml. Thank you!

**Comment by cvignac** [comment]
Hello, the configuration is in the `config/experiments/comm20.yaml` file.
You should run this command:
`CUDA_VISIBLE_DEVICES=0 python3 main.py +experiment=comm20 dataset=comm20 general.gpus=1`

**Comment by GhaliaRehawi** [comment]
I see, thanks a lot for the quick reply

**Comment by yikang613** [comment]
> Hello, the configuration is in the `config/experiments/comm20.yaml` file. You should run this command: `CUDA_VISIBLE_DEVICES=0 python3 main.py +experiment=comm20 dataset=comm20 general.gpus=1`

I have used this command but I am keep getting this error:
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for std::pair<double, double> already registered; second conversion method ignored.
Error executing job with overrides: ['+experiment=comm20', 'dataset=comm20', 'general.gpus=1']
 File "/gpfs52/data/maiziezhou_lab/yikang/gpu/DiGress/src/datasets/spectre_dataset.py", line 42, in download
    raise ValueError(f'Unknown dataset {self.dataset_name}')
ValueError: Unknown dataset comm-20
I tried to change the name from comm-20 to comm20 in the comm20.yaml. But it does not work.

**Comment by EasyZN** [comment]
Hi, I have met the same problem as:
ValueError: Unknown dataset comm-20

Do you figure out how to fix it?

> > Hello, the configuration is in the `config/experiments/comm20.yaml` file. You should run this command: `CUDA_VISIBLE_DEVICES=0 python3 main.py +experiment=comm20 dataset=comm20 general.gpus=1`
> 
> I have used this command but I am keep getting this error: :228: RuntimeWarning: to-Python converter for std::pair<double, double> already registered; second conversion method ignored. Error executing job with overrides: ['+experiment=comm20', 'dataset=comm20', 'general.gpus=1'] File "/gpfs52/data/maiziezhou_lab/yikang/gpu/DiGress/src/datasets/spectre_dataset.py", line 42, in download raise ValueError(f'Unknown dataset {self.dataset_name}') ValueError: Unknown dataset comm-20 I tried to change the name from comm-20 to comm20 in the comm20.yaml. But it does not work.

**Comment by cvignac** [comment]
Hello, I have replaced all the references to `comm-20` by `comm20`. It should hopefully fix the issue.
