### ISSUE TITLE
Validating on test data

### ISSUE THREAD

**Issue by AndreasBergmeister** [cvignac/DiGress#67]
The `forward` method of the `SpectreSamplingMetrics` class in `src/analysis/spectre_utils.py` has a `test` argument. This argument is not used, and all metrics are computed with respect to the test data, also during validation. 

Is this intentional?

**Comment by cvignac** [comment]
Hello, this issue has been fixed with the commit of September 13th. 

It is not super important because it did not affect the NLL (and therefore did not affect the choice of a particular checkpoint), but it was indeed a bug. Thanks for pointing it out!
