### ISSUE TITLE
Deriving the closed-form of the conditional true posterior

### ISSUE THREAD

**Issue by najwalb** [cvignac/DiGress#7]
In equation (1), you give the true posterior conditioned on $x$ as : $q(z^{t-1}|z^t, x) \propto z^t (Q^t)' \odot x \bar{Q}^{t-1}$, which I am guessing comes from Austin (2021)'s Equation 3: $q(z^{t-1}|z^t, x) = \frac{z^t (Q^t)' \odot x \bar{Q}^{t-1}}{x \bar{Q}^{t} (z^t)'}$.

I am not sure how to get this expression from the given definitions. Here is what I have so far:

$$
\begin{align}
q(z^{t-1}|z^t, x) &= \frac{q(z^t|z^{t-1},x) q(z^{t-1}|x)}{q(z^t|x)} \\
&=  \frac{z^{t-1} Q^t \odot x \bar{Q}^{t-1}}{x \bar{Q}^t} 
\end{align} 
$$

I am not sure how to get the $(z^t)'$ at the bottom or get rid of the $z^{t-1}$ at the top. Any help is appreciated!

Thanks in advance.

**Comment by cvignac** [comment]
You can forget the denominator, it's a normalization factor. Using Markov property, $q(z^t|z^{t-1},x)= q(z^t|z^{t-1})$. 
Now you apply Bayes rule again 
$q(z^t|z^{t-1}) \propto q(z^{t-1}| z^t) q(z^t)$ and notice that $q(z^{t-1}| z^t) = z^t (Q^t)'$. Finally, you notice that 
$q(z^t)$ does not depend on $z^{t-1}$, so it just goes in the normalization factor.

Clément
