### ISSUE TITLE
wrong with No process_path using dataset=guacamol

### ISSUE THREAD

**Issue by yuzhou2333** [cvignac/DiGress#75]
![image](https://github.com/cvignac/DiGress/assets/74141246/cba6cf38-f219-4145-8bc3-02063f4b6afb)

**Comment by asiraudin** [comment]
Hi,

Have you managed to fix this bug ?

**Comment by yuzhou2333** [comment]
> Hi,
> 
> Have you managed to fix this bug ?

This is because the inconformity in the guacamol_dataset.py in src.datasets
u can change the self.filter to self.filter_dataset,then u can run this code,if here have any other question,u can continue to contact to me~

**Comment by asiraudin** [comment]
Thank you for the quick answer !

I had indeed a problem in the processed_paths method, which caused the property not to be properly defined.

**Comment by yuzhou2333** [comment]
> Thank you for the quick answer !
> 
> I had indeed a problem in the processed_paths method, which caused the property not to be properly defined.

Yeah,it's because the inconformity between the self.filter and self.filter_dataset, i refer to the moses_dataset.py.Good luck~~
