### ISSUE TITLE
Training the regressor guidance

### ISSUE THREAD

**Issue by haoming-codes** [cvignac/DiGress#8]
It appears that the regressor is trained on the [real graphs](https://github.com/cvignac/DiGress/blob/guidance/src/guidance/train_qm9_regressor.py), where as in the original guided diffusion paper, the classifier is trained on the [noisy images](https://github.com/openai/guided-diffusion/blob/main/scripts/classifier_train.py). Is this intentional? Many thanks.

**Comment by cvignac** [comment]
We do train the regressor on the noisy data, as stated in the paper:

"Our method uses a regressor gη which is trained to predict target properties y of a clean graph G from a noisy version of G: gη(Gt) ≈ y(G)."

We are very happy of your interest in our work, but please double check the paper before opening Github issues :)

**Comment by haoming-codes** [comment]
Thanks, I did. If I understand correctly, you'd have to process the training data with `DiscreteDenoisingDiffusion.apply_noise()` before training the regressor, which is absent in [train_qm9_regressor.py](https://github.com/cvignac/DiGress/blob/guidance/src/guidance/train_qm9_regressor.py). I'm just trying to understand if there is a discrepancy between the code and the paper, or am I missing where this processing is done.
