### ISSUE TITLE
The checkpoint of Guacamol dataset

### ISSUE THREAD

**Issue by Layne-Huang** [cvignac/DiGress#9]
Hi,

Since your email address is unreachable, I apologise for sending the message here.

To better follow your work, could you please provide the checkpoint of Guacamol dataset?

Thankk you very much!

**Comment by cvignac** [comment]
Hello, I have added the checkpoint (the link is in the README). You'll need to revert to a previous commit to use it. Don't trust the likelihood that you obtain with previous commits, there are some bugs in the computation!

Clément

**Comment by Layne-Huang** [comment]
Thank you very much!

May I ask how many epochs you have trianed for the guacamole dataset? It is really big, and I noticed that you used the batch size 256 to train the model for 1000 epochs, which even Nvidia A100 cannot load such big batch size, and it is time consuming. In contrast, NGVAE only train 10 or 20 epochs to obtain good performance on this dataset.

Thank you for your attention.

**Comment by cvignac** [comment]
NGVAE has a FrechetChemNet score of 0.9/100. It means that the molecules it generates do not ressemble the dataset at all, so I don't agree that it works well (although the work is very interesting). 

The model ran for 113 epochs, which took pretty long to train (on one gpu it's more than a week).

**Comment by Layne-Huang** [comment]
Could you please provide other parameter settings? I trained the model on Guacamol for 180 epoch via 8 A100 gpus, however, the validity is only 75%.

Thank you very much!

**Comment by hasaki321** [comment]
@Layne-Huang 

Hello,

Are you still keeping the checkpoint of Guacamol? I will greatly appreicate it if you could send a copy to me!

Thank you
